# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_press_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='num',
        ),
    ]
