# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20181029_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Press')),
            ],
        ),
    ]
