# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
